CC = cc 
COPS = -pthread

all: assign4-part1 assign4-part2 assign4-part3 assign4-part4

assign4-part1: assign4-part1.c 
	$(CC) $(COPS) -o assign4-part1 assign4-part1.c

assign4-part2: assign4-part2.c 
	$(CC) $(COPS) -o assign4-part2 assign4-part2.c

assign4-part3: assign4-part3.c 
	$(CC) $(COPS) -o assign4-part3 assign4-part3.c

assign4-part4: assign4-part4.c 
	$(CC) $(COPS) -o assign4-part4 assign4-part4.c



clean:
	rm -f assign4-part1 assign4-part2 assign4-part3 assign4-part4 assign4-part1 *.o assign4-part2 *.o assign4-part3 *.o assign4-part4 *.o


